"""init

Revision ID: 80f59d8bd767
Revises: 
Create Date: 2023-11-02 00:00:05.332070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f59d8bd767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_api_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingest_timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('api_name', sa.String(length=64), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=False),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_api_data')
    # ### end Alembic commands ###
